#! /bin/sh
 
pkg=exuberant-ctags

set -e

if [ ! "$1" = "configure" ]; then
	exit 0
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ] ; then
	buffer=$(tempfile)
	for i in ctags etags ; do
		update-alternatives --display $i > "$buffer" || true
		if ! grep -q '\(exuberant|/usr/man\)' "$buffer" ; then
			update-alternatives --install /usr/bin/$i $i /usr/bin/ctags-exuberant 30 \
				--slave /usr/share/man/man1/$i.1.gz $i.1.gz /usr/share/man/man1/ctags-exuberant.1.gz
		fi
	done
	rm -f "$buffer"
fi

if [ "$1" = "configure" ] ; then
	if [ -d /usr/doc -a ! -e /usr/doc/$pkg -a -d /usr/share/doc/$pkg ]
	then
		ln -s ../share/doc/$pkg /usr/doc/$pkg
	fi
fi

exit 0

