#! /bin/sh

set -e

for i in ctags etags ; do
	update-alternatives --install /usr/bin/$i $i /usr/bin/ctags-exuberant 30 \
		--slave /usr/share/man/man1/$i.1.gz $i.1.gz /usr/share/man/man1/ctags-exuberant.1.gz
done

#DEBHELPER#

exit 0
